version = 1

test_patterns = [
  "*/tests/**",
  "**/*_test.go"
]

exclude_patterns = [
  "*/tests/**",
  "vendor/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/grafana/carbonapi"
  dependencies_vendored = true
