language: go
dist: xenial

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev mercurial pkg-config wget -y
  - make test
  - wget "https://raw.githubusercontent.com/go-graphite/helper-scripts/main/travis-docker-build.sh" && chmod +x ./travis-docker-build.sh
  - ./travis-docker-build.sh carbonapi

git:
  depth: 200

matrix:
  include:
    - go: "1.13.x"
    - go: "1.14.x"
      env:
        - BUILD_PACKAGES=true
