
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "bitbucket.org/tebeka/strftime"
  version = "0.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/JaderDias/movingmedian"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/dgryski/go-onlinestats"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/evmar/gocairo"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/grace"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/pidfile"

[[constraint]]
  name = "github.com/go-graphite/carbonzipper"
  version = "0.73.2"

[[constraint]]
  branch = "master"
  name = "github.com/gonum/matrix"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/lomik/og-rek"

[[constraint]]
  branch = "master"
  name = "github.com/lomik/zapwriter"

[[constraint]]
  branch = "master"
  name = "github.com/mjibson/go-dsp"

[[constraint]]
  branch = "master"
  name = "github.com/peterbourgon/g2g"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/wangjohn/quickselect"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.6.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
