
[[dependencies]]
  branch = "master"
  name = "github.com/JaderDias/movingmedian"

[[dependencies]]
  branch = "master"
  name = "github.com/dgryski/go-onlinestats"

[[dependencies]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[dependencies]]
  branch = "master"
  name = "github.com/evmar/gocairo"

[[dependencies]]
  branch = "master"
  name = "github.com/facebookgo/grace"

[[dependencies]]
  branch = "master"
  name = "github.com/facebookgo/pidfile"

[[dependencies]]
  branch = "refactor"
  name = "github.com/go-graphite/carbonzipper"

[[dependencies]]
  branch = "master"
  name = "github.com/gonum/matrix"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/handlers"

[[dependencies]]
  branch = "master"
  name = "github.com/kisielk/og-rek"

[[dependencies]]
  name = "github.com/lomik/zapwriter"
  revision = "d4499a33b5929c4a2e7e169165f594f35b39638c"

[[dependencies]]
  branch = "master"
  name = "github.com/mjibson/go-dsp"

[[dependencies]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[dependencies]]
  branch = "master"
  name = "github.com/wangjohn/quickselect"

[[dependencies]]
  branch = "master"
  name = "go.uber.org/zap"
