name: Build packages for Debian Bookworm

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [ main ]
    types:
      - completed
  push:
    tags:
      - v.*
jobs:
  build-packages-debian-bookworm:
    name: Build packages for Debian Bookworm
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - ^1
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Set up Ruby for package_cloud uploader to work
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - name: Install packaging dependencies
      run: |
        sudo apt-get install libcairo2-dev mercurial pkg-config wget -y
        gem install package_cloud
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create packages
      env:
        BUILD_PACKAGES: true
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      run: |
        wget "https://raw.githubusercontent.com/go-graphite/helper-scripts/main/build.sh" && chmod +x ./build.sh
        ./build.sh carbonapi "debian:bookworm"
